# Generated by Django 3.2.25 on 2025-09-23 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0006_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmenthead',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infra.department'),
        ),
    ]
